on:
  workflow_dispatch:
    inputs:
      coreVersion:
        description: "Version of the core. Must go with v"
        required: true
      dappmanagerVersion:
        description: "Version of the dappmanager. Only numbers"
      wifiVersion:
        description: "Version of the wifi. Only numbers"
      bindVersion:
        description: "Version of the bind. Only numbers"
      ipfsVersion:
        description: "Version of the ipfs. Only numbers"
      httpsVersion:
        description: "Version of the https. Only numbers"
      wireguardVersion:
        description: "Version of the wireguard. Only numbers"
      vpnVersion:
        description: "Version of the vpn. Only numbers"

jobs:
  pre-release:
    name: create pre release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out installer
        uses: actions/checkout@master
        with:
          repository: dappnode/DAppNode_Installer
      - name: Set new versions
        run: |
          [ ! -z "$INPUT_BINDVERSION" ] && sed -i -e "/BIND_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${INPUT_BINDVERSION}"/" .dappnode_profile.sh
          [ ! -z "$INPUT_IPFSVERSION" ] && sed -i -e "/IPFS_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${INPUT_IPFSVERSION}"/" .dappnode_profile.sh
          [ ! -z "$INPUT_VPNVERSION" ] && sed -i -e "/VPN_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${INPUT_VPNVERSION}"/" .dappnode_profile.sh
          [ ! -z "$INPUT_DAPPMANAGERVERSION" ] && sed -i -e "/DAPPMANAGER_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${INPUT_DAPPMANAGERVERSION}"/" .dappnode_profile.sh
          [ ! -z "$INPUT_WIFIVERSION" ] && sed -i -e "/WIFI_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${INPUT_WIFIVERSION}"/" .dappnode_profile.sh
          [ ! -z "$INPUT_WIREGUARDVERSION" ] && sed -i -e "/WIREGUARD_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${INPUT_WIREGUARDVERSION}"/" .dappnode_profile.sh
          [ ! -z "$INPUT_HTTPSVERSION" ] && sed -i -e "/HTTPS_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${INPUT_HTTPSVERSION}"/" .dappnode_profile.sh
      - name: Build
        run: |
          docker-compose build
          docker-compose up
      - name: Check iso
        run: |
          ls -lrt images/DAppNode-debian-bullseye-amd64.iso

      - name: Create dappnode_profile.sh
        run: |
          cp .dappnode_profile dappnode_profile.sh
      - name: Pre release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${INPUT_COREVERSION}
          prerelease: true
          files: |
            ./images/DAppNode-debian-bullseye-amd64.iso
            ./scripts/dappnode_install.sh
            ./scripts/dappnode_install_pre.sh
            ./scripts/dappnode_uninstall.sh
            ./scripts/dappnode_access_credentials.sh
            dappnode_profile.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
