name: Pre-release
on:
  workflow_dispatch:
    inputs:
      core:
        description: "Version of the core. Must go with v (e.g v0.2.47)"
        required: true
      dappmanager:
        description: "Version of the dappmanager. Only numbers"
        required: true
      wifi:
        description: "Version of the wifi. Only numbers"
        required: true
      bind:
        description: "Version of the bind. Only numbers"
        required: true
      ipfs:
        description: "Version of the ipfs. Only numbers"
        required: true
      https:
        description: "Version of the https. Only numbers"
        required: true
      wireguard:
        description: "Version of the wireguard. Only numbers"
        required: true
      vpn:
        description: "Version of the vpn. Only numbers"
        required: true

env:
  BIND_VERSION: ${{ github.event.inputs.bind }}
  IPFS_VERSION: ${{ github.event.inputs.ipfs }}
  DAPPMANAGER_VERSION: ${{ github.event.inputs.dappmanager }}
  WIFI_VERSION: ${{ github.event.inputs.wifi }}
  WIREGUARD_VERSION: ${{ github.event.inputs.wireguard }}
  HTTPS_VERSION: ${{ github.event.inputs.https }}
  VPN_VERSION: ${{ github.event.inputs.vpn }}
  CORE_VERSION: ${{ github.event.inputs.core }}

jobs:
  pre-release:
    name: create pre release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out installer
        uses: actions/checkout@master
        with:
          repository: dappnode/DAppNode_Installer
      - name: Set new versions
        run: |
          sed -i -e "/BIND_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${BIND_VERSION}"/" .dappnode_profile
          sed -i -e "/IPFS_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${IPFS_VERSION}"/" .dappnode_profile
          sed -i -e "/VPN_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${VPN_VERSION}"/" .dappnode_profile
          sed -i -e "/DAPPMANAGER_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${DAPPMANAGER_VERSION}"/" .dappnode_profile
          sed -i -e "/WIFI_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${WIFI_VERSION}"/" .dappnode_profile
          sed -i -e "/WIREGUARD_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${WIREGUARD_VERSION}"/" .dappnode_profile
          sed -i -e "/HTTPS_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${HTTPS_VERSION}"/" .dappnode_profile
          cat .dappnode_profile
        env:
          BIND_VERSION: ${{ env.BIND_VERSION }}
          IPFS_VERSION: ${{ env.IPFS_VERSION }}
          DAPPMANAGER_VERSION: ${{ env.DAPPMANAGER_VERSION }}
          WIFI_VERSION: ${{ env.WIFI_VERSION }}
          WIREGUARD_VERSION: ${{ env.WIREGUARD_VERSION }}
          HTTPS_VERSION: ${{ env.HTTPS_VERSION }}
          VPN_VERSION: ${{ env.VPN_VERSION }}

      - name: Build
        run: |
          docker-compose build
          docker-compose up

      - name: Check iso
        run: |
          ls -lrt images/DAppNode-debian-bullseye-amd64.iso

      - name: Create dappnode_profile.sh
        run: |
          cp .dappnode_profile dappnode_profile.sh

      - name: Set DAppNode ISO name
        run: |
          mv ./images/DAppNode-debian-bullseye-amd64.iso ./DAppNode-${CORE_VERSION}-debian-bullseye-amd64.iso

      # echo ::set-env name=SHASUM_ARM::$(shasum -a 256 DAppNode-${CORE_VERSION}-debian-bullseye-amd64.iso)
      - name: Get SHA-256
        id: shasum
        run: |
          echo ::set-output name=SHASUM_AMD::$(shasum -a 256 DAppNode-${CORE_VERSION}-debian-bullseye-amd64.iso)
        env:
          CORE_VERSION: ${{ env.CORE_VERSION }}

      - name: Pre release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.core }}
          prerelease: true
          files: |
            ./DAppNode-*-amd64.iso
            ./scripts/dappnode_install.sh
            ./scripts/dappnode_install_pre.sh
            ./scripts/dappnode_uninstall.sh
            ./scripts/dappnode_access_credentials.sh
            dappnode_profile.sh
          body: |
            # Versions
            |  Package  | Version  | 
            |---|---|
            |bind.dnp.dappnode.eth|${BIND_VERSION}|
            |ipfs.dnp.dappnode.eth|${IPFS_VERSION}|
            |vpn.dnp.dappnode.eth |${VPN_VERSION}|
            |dappmanager.dnp.dappnode.eth|${DAPPMANAGER_VERSION}|
            |wifi.dnp.dappnode.eth|${WIFI_VERSION}|
            |https.dnp.dappnode.eth|${HTTPS_VERSION}|
            |wireguard.dnp.dappnode.eth|${WIREGUARD_VERSION}|

            # Changes
            # ISO SHA-256 Checksum
            ```
            ${SHASUM}
            ```
            # DAppNode for Raspberry Pi 4 64bit
            [Instructions](https://github.com/dappnode/DAppNode/wiki/DAppNodeARM-Installation-Guide)
            * default login data:
                * __user__: dappnode
                * __password__: dappnodepi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHASUM: ${{ steps.shasum.outputs.SHASUM_AMD }}
          # Versions
          BIND_VERSION: ${{ env.BIND_VERSION }}
          IPFS_VERSION: ${{ env.IPFS_VERSION }}
          DAPPMANAGER_VERSION: ${{ env.DAPPMANAGER_VERSION }}
          WIFI_VERSION: ${{ env.WIFI_VERSION }}
          WIREGUARD_VERSION: ${{ env.WIREGUARD_VERSION }}
          HTTPS_VERSION: ${{ env.HTTPS_VERSION }}
          VPN_VERSION: ${{ env.VPN_VERSION }}
