on:
  workflow_dispatch:
    inputs:
      core:
        description: "Version of the core. Must go with v"
        required: true
      dappmanager:
        description: "Version of the dappmanager. Only numbers"
      wifi:
        description: "Version of the wifi. Only numbers"
      bind:
        description: "Version of the bind. Only numbers"
      ipfs:
        description: "Version of the ipfs. Only numbers"
      https:
        description: "Version of the https. Only numbers"
      wireguard:
        description: "Version of the wireguard. Only numbers"
      vpn:
        description: "Version of the vpn. Only numbers"

jobs:
  pre-release:
    name: create pre release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out installer
        uses: actions/checkout@master
        with:
          repository: dappnode/DAppNode_Installer
      - name: Debug, print envs
        run: |
          echo "BIND: ${{ github.event.inputs.bind }}"
          echo "CORE: ${{ github.event.inputs.core }}"
      - name: Set new versions
        run: |
          [ ! -z "$INPUT_BIND" ] && sed -i -e "/BIND_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${INPUT_BIND}"/" .dappnode_profile.sh
          [ ! -z "$INPUT_IPFS" ] && sed -i -e "/IPFS_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${INPUT_IPFS}"/" .dappnode_profile.sh
          [ ! -z "$INPUT_VPN" ] && sed -i -e "/VPN_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${INPUT_VPN}"/" .dappnode_profile.sh
          [ ! -z "$INPUT_DAPPMANAGER" ] && sed -i -e "/DAPPMANAGER_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${INPUT_DAPPMANAGER}"/" .dappnode_profile.sh
          [ ! -z "$INPUT_WIFI" ] && sed -i -e "/WIFI_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${INPUT_WIFI}"/" .dappnode_profile.sh
          [ ! -z "$INPUT_WIREGUARD" ] && sed -i -e "/WIREGUARD_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${INPUT_WIREGUARD}"/" .dappnode_profile.sh
          [ ! -z "$HTTPS" ] && sed -i -e "/HTTPS_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${INPUT_HTTPS}"/" .dappnode_profile.sh
      - name: Build
        run: |
          docker-compose build
          docker-compose up
      - name: Check iso
        run: |
          ls -lrt images/DAppNode-debian-bullseye-amd64.iso

      - name: Create dappnode_profile.sh
        run: |
          cp .dappnode_profile dappnode_profile.sh
      - name: Pre release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${INPUT_COREVERSION}
          prerelease: true
          files: |
            ./images/DAppNode-debian-bullseye-amd64.iso
            ./scripts/dappnode_install.sh
            ./scripts/dappnode_install_pre.sh
            ./scripts/dappnode_uninstall.sh
            ./scripts/dappnode_access_credentials.sh
            dappnode_profile.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
