name: Pre-release
on:
  workflow_dispatch:
    inputs:
      core:
        description: "Version of the core. Must go with v (e.g v0.2.47)"
        required: true
      dappmanager:
        description: "Version of the dappmanager. Only numbers"
        required: true
      wifi:
        description: "Version of the wifi. Only numbers"
        required: true
      bind:
        description: "Version of the bind. Only numbers"
        required: true
      ipfs:
        description: "Version of the ipfs. Only numbers"
        required: true
      https:
        description: "Version of the https. Only numbers"
        required: true
      wireguard:
        description: "Version of the wireguard. Only numbers"
        required: true
      vpn:
        description: "Version of the vpn. Only numbers"
        required: true

env:
  BIND_VERSION: ${{ github.event.inputs.bind }}
  IPFS_VERSION: ${{ github.event.inputs.ipfs }}
  DAPPMANAGER_VERSION: ${{ github.event.inputs.dappmanager }}
  WIFI_VERSION: ${{ github.event.inputs.wifi }}
  WIREGUARD_VERSION: ${{ github.event.inputs.wireguard }}
  HTTPS_VERSION: ${{ github.event.inputs.https }}
  VPN_VERSION: ${{ github.event.inputs.vpn }}
  CORE_VERSION: ${{ github.event.inputs.core }}

jobs:
  pre-release:
    name: create pre release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out installer
        uses: actions/checkout@master
        with:
          repository: dappnode/DAppNode_Installer
      - name: Set new versions
        run: |
          sed -i -e "/BIND_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${BIND_VERSION}"/" .dappnode_profile
          sed -i -e "/IPFS_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${IPFS_VERSION}"/" .dappnode_profile
          sed -i -e "/VPN_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${VPN_VERSION}"/" .dappnode_profile
          sed -i -e "/DAPPMANAGER_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${DAPPMANAGER_VERSION}"/" .dappnode_profile
          sed -i -e "/WIFI_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${WIFI_VERSION}"/" .dappnode_profile
          sed -i -e "/WIREGUARD_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${WIREGUARD_VERSION}"/" .dappnode_profile
          sed -i -e "/HTTPS_VERSION/s/[0-9]*\.[0-9]*\.[0-9]*/"${HTTPS_VERSION}"/" .dappnode_profile
          cat .dappnode_profile

      # ISO ATTENDED
      - name: Build attended
        run: |
          sed -i -e "/UNATTENDED/s/true/false/" docker-compose.yml 
          docker-compose build
          docker-compose up

      - name: Check iso attended
        run: |
          ls -lrt images/DAppNode-debian-bullseye-amd64.iso

      - name: Set DAppNode attended ISO name
        run: |
          cp ./images/DAppNode-debian-bullseye-amd64.iso DAppNode-${CORE_VERSION}-debian-bullseye-amd64.iso

      # ISO UNATTENDED
      - name: Build unattended
        run: |
          sed -i -e "/UNATTENDED/s/false/true/" docker-compose.yml
          docker-compose build
          docker-compose up

      - name: Check iso unattended
        run: |
          ls -lrt images/DAppNode-debian-bullseye-amd64.iso

      - name: Set DAppNode unttended ISO name
        run: |
          cp ./images/DAppNode-debian-bullseye-amd64.iso DAppNode-${CORE_VERSION}-debian-bullseye-amd64-unattended.iso

      # Profile
      - name: Create dappnode_profile.sh
        run: |
          cp .dappnode_profile dappnode_profile.sh

      # SHASUMs
      - name: Get SHA-256 attended
        id: shasum-attended
        run: |
          SHASUM_ATTENDED=$(shasum -a 256 DAppNode-${CORE_VERSION}-debian-bullseye-amd64.iso)
          echo "::set-output name=SHASUM_ATTENDED::$SHASUM_ATTENDED"

      - name: Get SHA-256 unattended
        id: shasum-unattended
        run: |
          SHASUM_UNATTENDED=$(shasum -a 256 DAppNode-${CORE_VERSION}-debian-bullseye-amd64-unattended.iso)
          echo "::set-output name=SHASUM_UNATTENDED::$SHASUM_UNATTENDED"

      # Release body
      - name: Write release content
        run: |
          echo -en "# Versions\n|  Package  | Version  |\n|---|---|\nbind.dnp.dappnode.eth|${BIND_VERSION}|\n|ipfs.dnp.dappnode.eth|${IPFS_VERSION}|\n|vpn.dnp.dappnode.eth |${VPN_VERSION}|\n|dappmanager.dnp.dappnode.eth|${DAPPMANAGER_VERSION}|\n|wifi.dnp.dappnode.eth|${WIFI_VERSION}|\n|https.dnp.dappnode.eth|${HTTPS_VERSION}|\n|wireguard.dnp.dappnode.eth|${WIREGUARD_VERSION}|\n# Changes\n# ISO SHA-256 Checksum\n## Attended version\n\`\`\`\nshasum -a 256 DAppNode-${CORE_VERSION}-debian-bullseye-amd64.iso\n${SHASUM_ATTENDED}\n\`\`\`\n## Unattended version\ndefault login data:\n  **__user__**: dappnode\n  **__password__**: dappnode.s0\n**_Warning_**: This ISO will install dappnode automatically, deleting all existin partitions in the disk\n\`\`\`\nshasum -a 256 DAppNode-${CORE_VERSION}-debian-bullseye-amd64.iso\n${SHASUM_UNATTENDED}\n\`\`\`\n# DAppNode for Raspberry Pi 4 64bit\n[Instructions](https://github.com/dappnode/DAppNode/wiki/DAppNodeARM-Installation-Guide)\ndefault login data:\n  **__user__**: dappnode\n  **__password__**: dappnodepi" > CHANGELOG.md
          cat CHANGELOG.md
        env:
          SHASUM_ATTENDED: ${{ steps.shasum-attended.outputs.SHASUM_ATTENDED }}
          SHASUM_UNATTENDED: ${{ steps.shasum-unattended.outputs.SHASUM_UNATTENDED }}

      # PRE-RELEASE ASSETS
      - name: Pre release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.core }}
          prerelease: true
          files: |
            ./DAppNode-*-amd64.iso
            ./DAppNode-*-amd64-unattended.iso
            ./scripts/dappnode_install.sh
            ./scripts/dappnode_install_pre.sh
            ./scripts/dappnode_uninstall.sh
            ./scripts/dappnode_access_credentials.sh
            dappnode_profile.sh
          body_path: CHANGELOG.md

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
